import type { Metadata } from "next";
import { Signika, Heebo } from "next/font/google";
import "./globals.css";
import { SessionProvider } from './Apis/AppContext'
import { Toaster } from 'react-hot-toast'

const geistMono = Signika({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wellness project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
